[package]
name    = "ex25_find_program_address_solution"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "ex25_find_program_address"

[dependencies]
anchor-lang = { workspace = true }

[dev-dependencies]
anchorlings_test_kit = { workspace = true }
solana-program-test  = { workspace = true }
solana-sdk           = { workspace = true }
tokio                = { workspace = true }

[lints]
workspace = true
