use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111112");

#[program]
pub mod ex03_entry_handler {
    use super::*;

    // TODO: every Anchor handler must return `Result<()>`. The dispatcher
    // generated by `#[program]` propagates errors using `?`, so a handler
    // returning `()` won't satisfy it.
    //
    // Fix the signature *and* the body — return `Ok(())`.
    pub fn ping(_ctx: Context<Ping>) -> {
    }
}

#[derive(Accounts)]
pub struct Ping {}
